<h3checking version of numPy and pandas></h3>

<h2>Roll No : CO2032 Name : Nishagiri Dattatray Kamble</h2>

<h1>pandas</h1>

<h3>~Checking version NumPy and Pandas</h3>

In [1]:
import numpy as np
import pandas as pd

print("Pandas Version :",pd.__version__)
print("Numpy Version :",np.__version__)

Pandas Version : 2.3.1
Numpy Version : 1.26.4

<h3>~create a serii from list</h3>

In [16]:
#create a serii from list

lst = ['Nisha',2]
s=pd.Series(lst)
print(s)

0    Apple
1        2
dtype: object

<h3>~create with custom index</h3>

In [17]:

a = ['Nisha',43]
s = pd.Series(a, index=['a','c'])
print(s)

a    Nisha
c       43
dtype: object

<h3>~create with numpy array</h3>

In [21]:

n = np.array(['Nisha', 3])
print(type(n))
df = pd.Series(n, index=[1, 2])
print(df)

<class 'numpy.ndarray'>
1    Nisha
2        3
dtype: object

In [29]:
n = np.array(['Nishuu', 'sanuu', 'khushiii'])
print(type(n))
df =pd.Series(n, index=['row1', 'row2', 'row3'])
df

<class 'numpy.ndarray'>

row1      Nishuu
row2       sanuu
row3    khushiii
dtype: object

<h3>~create a series from dictionary</h3>

In [32]:

df_dict = {'a':[2,3,4], 'b':[5,6,7]}
s = pd.Series(df_dict)
s

a    [2, 3, 4]
b    [5, 6, 7]
dtype: object

In [5]:
data = ['Aplle', 2, 3.5]


py_list = data 
py_dict= {'item':'Aplle', 'count':2 , 'price':3.5}
np_arr = np.array(data , dtype=object)
pd_Series= pd.Series(data, index=['item','count','price'])


print("List :" ,py_list)
print("Dict :" , py_dict)
print("NumPy arr :", np_arr)

print(pd_Series)

List : ['Aplle', 2, 3.5]
Dict : {'item': 'Aplle', 'count': 2, 'price': 3.5}
NumPy arr : ['Aplle' 2 3.5]
item     Aplle
count        2
price      3.5
dtype: object

In [9]:
data =['nisha' , 18, 31]

py_list =data
py_dict = {'name':'nisha', 'Age': 18, 'Roll No': 31}
np_arr= np.array(data, dtype=object)
pd_Series=pd.Series(data, index=['name', 'Age', 'Roll No'])


print("LIst :", py_list)
print("Dict :", py_dict)
print("NumPy Arr :",np_arr)
print("pandas :", pd_Series)

LIst : ['nisha', 18, 31]
Dict : {'name': 'nisha', 'Age': 18, 'Roll No': 31}
NumPy Arr : ['nisha' 18 31]
pandas : name       nisha
Age           18
Roll No       31
dtype: object

In [21]:
import pandas as pd

data = ['Nisha', 2]

t = pd.Series(data)

print(t)

0    Nisha
1        2
dtype: object

In [27]:
lst = ['Apple', 2]

s = pd.Series(data , index=[1,2])
print(s)

1    Nisha
2        2
dtype: object

In [5]:
import numpy as np
import pandas as pd


s = {'col1': [1, 2]}
df_dict = pd.DataFrame(s)
print(df_dict)
print(type(df_dict))
print("shape :", df_dict.shape)

   col1
0     1
1     2
<class 'pandas.core.frame.DataFrame'>
shape : (2, 1)

In [6]:
data = [[1, 2, 3], [4, 5, 6]]
df = pd.DataFrame(data, columns=['col1', 'col2', 'col3'])
print(df)

   col1  col2  col3
0     1     2     3
1     4     5     6

In [7]:
arr = np.array([['a', 'b', 'c'], ['d', 'f', 'e']])
df_arr = pd.DataFrame(arr, columns=['col1', 'col2', 'col3'])
print(df_arr)

  col1 col2 col3
0    a    b    c
1    d    f    e

In [16]:

df_dict =pd.DataFrame({
    'Name' : ['Nisha', 'Sandhya', 'Aru'],
    'Roll No' : [101,102,103],
    'Marks': [95, 99, 98]})
df_dict

      Name  Roll No  Marks
0    Nisha      101     95
1  Sandhya      102     99
2      Aru      103     98

<h3>~For School Teacher</h3>

In [22]:


df_shl = pd.DataFrame({
    'Teacher Name': ['nishhh', 'sandyyy', 'sanyaa', 'khushii'],
    'Subject':['Python', 'Java', 'Js', 'node.js'],
    'Experiance Year':[50, 40, 12, 18]})
df_shl

  Teacher Name  Subject  Experiance Year
0       nishhh   Python               50
1      sandyyy     Java               40
2       sanyaa       Js               12
3      khushii  node.js               18

<h3>~employeee salary</h3>

In [21]:


df_emp = pd.DataFrame({
    'emp_id':[11,22,33,44],
    'name': ['a', 'b', 'c', 'd'],
    'salary': [10000, 11000, 11500,20000]})
df_emp

   emp_id name  salary
0      11    a   10000
1      22    b   11000
2      33    c   11500
3      44    d   20000

<h3>~Combinin  DataFrames</h3>

In [24]:

df_shl = pd.DataFrame({
    'Teacher Name': ['nishhh', 'sandyyy', 'sanyaa', 'khushii'],
    'Subject':['Python', 'Java', 'Js', 'node.js'],
    'Experiance Year':[50, 40, 12, 18]})
df_emp = pd.DataFrame({
    'emp_id':[11,22,33,44],
    'name': ['a', 'b', 'c', 'd'],
    'salary': [10000, 11000, 11500,20000]})

print(df_shl)
print()
print(df_emp)

  Teacher Name  Subject  Experiance Year
0       nishhh   Python               50
1      sandyyy     Java               40
2       sanyaa       Js               12
3      khushii  node.js               18

   emp_id name  salary
0      11    a   10000
1      22    b   11000
2      33    c   11500
3      44    d   20000

In [27]:
pd.concat([df_shl, df_emp], ignore_index=True)

  Teacher Name  Subject  Experiance Year  emp_id name   salary
0       nishhh   Python             50.0     NaN  NaN      NaN
1      sandyyy     Java             40.0     NaN  NaN      NaN
2       sanyaa       Js             12.0     NaN  NaN      NaN
3      khushii  node.js             18.0     NaN  NaN      NaN
0          NaN      NaN              NaN    11.0    a  10000.0
1          NaN      NaN              NaN    22.0    b  11000.0
2          NaN      NaN              NaN    33.0    c  11500.0
3          NaN      NaN              NaN    44.0    d  20000.0

In [28]:
pd.concat([df_shl, df_emp], axis=1)

  Teacher Name  Subject  Experiance Year  emp_id name  salary
0       nishhh   Python               50      11    a   10000
1      sandyyy     Java               40      22    b   11000
2       sanyaa       Js               12      33    c   11500
3      khushii  node.js               18      44    d   20000

In [29]:
pd.concat([df_shl, df_emp], axis=0)

  Teacher Name  Subject  Experiance Year  emp_id name   salary
0       nishhh   Python             50.0     NaN  NaN      NaN
1      sandyyy     Java             40.0     NaN  NaN      NaN
2       sanyaa       Js             12.0     NaN  NaN      NaN
3      khushii  node.js             18.0     NaN  NaN      NaN
0          NaN      NaN              NaN    11.0    a  10000.0
1          NaN      NaN              NaN    22.0    b  11000.0
2          NaN      NaN              NaN    33.0    c  11500.0
3          NaN      NaN              NaN    44.0    d  20000.0

<h3>~Using concat , merge , join</h3>

In [9]:

df_shl = pd.DataFrame({
    'Teacher Name': ['nishhh', 'sandyyy', 'sanyaa', 'khushii'],
    'Subject':['Python', 'Java', 'Js', 'node.js'],
    'Experiance Year':[50, 40, 12, 18],
'salary': [12000,50000,60000,34000]})
df_emp = pd.DataFrame({
    'emp_id':[11,22,33,44],
    'name': ['a', 'b', 'c', 'd'],
    'salary': [10000, 11000, 11500,20000]})

print(df_shl)
print()
print(df_emp)

  Teacher Name  Subject  Experiance Year  salary
0       nishhh   Python               50   12000
1      sandyyy     Java               40   50000
2       sanyaa       Js               12   60000
3      khushii  node.js               18   34000

   emp_id name  salary
0      11    a   10000
1      22    b   11000
2      33    c   11500
3      44    d   20000

In [10]:
pd.merge(df_shl, df_emp, on='salary', how='outer')

  Teacher Name  Subject  Experiance Year  salary  emp_id name
0          NaN      NaN              NaN   10000    11.0    a
1          NaN      NaN              NaN   11000    22.0    b
2          NaN      NaN              NaN   11500    33.0    c
3       nishhh   Python             50.0   12000     NaN  NaN
4          NaN      NaN              NaN   20000    44.0    d
5      khushii  node.js             18.0   34000     NaN  NaN
6      sandyyy     Java             40.0   50000     NaN  NaN
7       sanyaa       Js             12.0   60000     NaN  NaN

In [11]:
pd.merge(df_shl, df_emp, on='salary', how='inner')

Empty DataFrame
Columns: [Teacher Name, Subject, Experiance Year, salary, emp_id, name]
Index: []

In [14]:
pd.merge(df_shl, df_emp, on='salary', how='left')

  Teacher Name  Subject  Experiance Year  salary  emp_id name
0       nishhh   Python               50   12000     NaN  NaN
1      sandyyy     Java               40   50000     NaN  NaN
2       sanyaa       Js               12   60000     NaN  NaN
3      khushii  node.js               18   34000     NaN  NaN

In [15]:
pd.merge(df_shl, df_emp, on='salary', how='right')

  Teacher Name Subject  Experiance Year  salary  emp_id name
0          NaN     NaN              NaN   10000      11    a
1          NaN     NaN              NaN   11000      22    b
2          NaN     NaN              NaN   11500      33    c
3          NaN     NaN              NaN   20000      44    d

In [40]:
temp_df=pd.DataFrame({'city':['mum','del','hyd','bang'], 'temp':[22,33,44,55]})
hum_df=pd.DataFrame({'city':['mum','del','chen','hyd'], 'hum':[12,89,45,94]})
print(temp_df)
print()
print(hum_df)

   city  temp
0   mum    22
1   del    33
2   hyd    44
3  bang    55

   city  hum
0   mum   12
1   del   89
2  chen   45
3   hyd   94

In [41]:
pd.concat([temp_df,hum_df], ignore_index=True)

   city  temp   hum
0   mum  22.0   NaN
1   del  33.0   NaN
2   hyd  44.0   NaN
3  bang  55.0   NaN
4   mum   NaN  12.0
5   del   NaN  89.0
6  chen   NaN  45.0
7   hyd   NaN  94.0

In [42]:
pd.concat([temp_df,hum_df], axis=1)

   city  temp  city  hum
0   mum    22   mum   12
1   del    33   del   89
2   hyd    44  chen   45
3  bang    55   hyd   94

In [43]:
pd.merge(temp_df,hum_df, on='city', how='outer')

   city  temp   hum
0  bang  55.0   NaN
1  chen   NaN  45.0
2   del  33.0  89.0
3   hyd  44.0  94.0
4   mum  22.0  12.0

In [44]:
pd.merge(temp_df,hum_df, on='city', how='inner')

  city  temp  hum
0  mum    22   12
1  del    33   89
2  hyd    44   94

In [50]:
print(pd.merge(temp_df,hum_df, on='city', how='outer'))
print()
print(pd.merge(temp_df,hum_df, on='city', how='inner'))

   city  temp   hum
0  bang  55.0   NaN
1  chen   NaN  45.0
2   del  33.0  89.0
3   hyd  44.0  94.0
4   mum  22.0  12.0

  city  temp  hum
0  mum    22   12
1  del    33   89
2  hyd    44   94

In [61]:
left=temp_df.set_index('city')
right=hum_df.set_index('city')
left.join(right, how='inner')

      temp  hum
city
mum     22   12
del     33   89
hyd     44   94

<h3>~Emporting & Exporting Datasets</h3>

In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(42)

df=pd.DataFrame({
     "Name":["Nisha","Sandyy","Khushii","Raj","Aruu"],
    "Age":[21,22,20,23,21],
    "Marks":[80,90,75,88,95]
})

print("Original Data")
print()
print(df)

Original Data

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

<h3>Exporting</h3>

In [4]:
df.to_csv("students.csv", index=False)
print("\nFiles created successfully!")

df

Files created successfully!

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

In [10]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df.to_excel("students.xlsx", index=False)
print("\nFiles created successfully!")

df

Files created successfully!

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

In [6]:
df.to_json("students.json", orient="records")
print("\nFiles created successfully!")

df

Files created successfully!

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

<h3>Read Files</h3>

In [38]:
csv_data = pd.read_csv("students.csv")
csv_data

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

In [39]:
excel_data = pd.read_excel("students.xlsx")
excel_data

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

In [42]:
json_data = pd.read_json("students.json")
json_data

    Name  Age  Marks
0   Amit   21     80
1   Neha   22     90
2   Riya   20     75
3    Raj   23     88
4  Priya   21     95

In [43]:
print("CSV Data")
print()
print(csv_data)
print() 
print("Shape:", csv_data.shape)

CSV Data

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

Shape: (5, 3)

In [44]:
print("Excel Data")
print()
print(excel_data)
print() 
print("Shape:", excel_data.shape)

Excel Data

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88
4     Aruu   21     95

Shape: (5, 3)

In [46]:
print("JSON Data")
print()
print(json_data)
print()    
print("Shape:", json_data.shape)

JSON Data

    Name  Age  Marks
0   Amit   21     80
1   Neha   22     90
2   Riya   20     75
3    Raj   23     88
4  Priya   21     95

Shape: (5, 3)

<h3>~DataFrame Attributes</h3>

In [35]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Nisha","Sandyy","Khushii","Raj","Aruu"],
    "Age": [21, 22, 20, 23, 21],
    "Marks": [80, 90, 75, 88, 95],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Nashik"]
})
print()

print(df)

      Name  Age  Marks    City
0    Nisha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Aruu   21     95  Nashik

In [36]:

print(df.shape)  #Returns the number of rows and columns

(5, 4)

In [37]:
print(df.size)  #total number of values in the DataFrame

20

In [38]:
print(df.ndim)  #number of dimensions.

2

In [39]:
print(df.dtypes)  #data type of each column

Name     object
Age       int64
Marks     int64
City     object
dtype: object

In [40]:
print(df.columns)   #Displays all column names

Index(['Name', 'Age', 'Marks', 'City'], dtype='object')

In [41]:
print(list(df.columns))   #convert it into a list

['Name', 'Age', 'Marks', 'City']

In [42]:
print(df.index)   #row numbers

RangeIndex(start=0, stop=5, step=1)

In [43]:
print(df.values)  #only the data return

[['Nisha' 21 80 'Pune']
 ['Sandyy' 22 90 'Mumbai']
 ['Khushii' 20 75 'Delhi']
 ['Raj' 23 88 'Pune']
 ['Aruu' 21 95 'Nashik']]

In [44]:
print(df.axes)  #row index and column names

[RangeIndex(start=0, stop=5, step=1), Index(['Name', 'Age', 'Marks', 'City'], dtype='object')]

In [45]:
print(df.keys())  #Same as df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='object')

In [46]:
df.info() #most important methods in Pandas  whenever you load a new dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [47]:
df.describe()  #statistics for numeric columns

             Age      Marks
count   5.000000   5.000000
mean   21.400000  85.600000
std     1.140175   8.018728
min    20.000000  75.000000
25%    21.000000  80.000000
50%    21.000000  88.000000
75%    22.000000  90.000000
max    23.000000  95.000000

In [48]:
df.describe(include="object")  #statistics for text (categorical) columns

         Name  City
count       5     5
unique      5     4
top     Nisha  Pune
freq        1     2

<h3>~selecting and Indexing</h3>

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Nisha","Sandyy","Khushii","Raj","Aruu"],
    "Age": [21, 22, 20, 23, 21],
    "Marks": [80, 90, 75, 88, 95],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Nashik"]
})
print()

print(df)

      Name  Age  Marks    City
0    Nisha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Aruu   21     95  Nashik

<h2>iloc :</h2>

In [7]:
df.iloc[0]  #Position-based selection

Name     Nisha
Age         21
Marks       80
City      Pune
Name: 0, dtype: object

In [5]:
df.iloc[-1]    #Last row

Name       Aruu
Age          21
Marks        95
City     Nashik
Name: 4, dtype: object

In [8]:
df.iloc[[1,3]]  #Specific row

     Name  Age  Marks    City
1  Sandyy   22     90  Mumbai
3     Raj   23     88    Pune

In [11]:
df.iloc[0:3,0:2]  #rows and Columns   0:3 → Rows 0,1,2  0:2 → Columns 0,1

      Name  Age
0    Nisha   21
1   Sandyy   22
2  Khushii   20

<h2>loc :</h2>

In [12]:
df.loc[0]   #Label-based selection

Name     Nisha
Age         21
Marks       80
City      Pune
Name: 0, dtype: object

In [13]:
df.loc[[1,2]]   #ultiple rows

      Name  Age  Marks    City
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi

In [14]:
df.loc[:, "Age"]  #select one column

0    21
1    22
2    20
3    23
4    21
Name: Age, dtype: int64

In [15]:
df.loc[:, ["Name","Marks"]]   #multiple columns

      Name  Marks
0    Nisha     80
1   Sandyy     90
2  Khushii     75
3      Raj     88
4     Aruu     95

In [17]:
df.loc[1:3, "Name":"Marks"]    #select rows and column    #loc includes the ending value.

      Name  Age  Marks
1   Sandyy   22     90
2  Khushii   20     75
3      Raj   23     88

<h3>Boolean Indexing</h3>

In [18]:
df[df["Age"] > 21]    #Students whose age is greater than 21

     Name  Age  Marks    City
1  Sandyy   22     90  Mumbai
3     Raj   23     88    Pune

In [19]:
df[df["Marks"] > 85]   #Marks greater than 85

     Name  Age  Marks    City
1  Sandyy   22     90  Mumbai
3     Raj   23     88    Pune
4    Aruu   21     95  Nashik

<h2>~Multiple Conditions</h2>

In [20]:
df[(df["Age"]>21) & (df["Marks"]>85)]

     Name  Age  Marks    City
1  Sandyy   22     90  Mumbai
3     Raj   23     88    Pune

In [23]:
df[(df["City"]=="Pune") | (df["Marks"]>90)]   #OR condition

    Name  Age  Marks    City
0  Nisha   21     80    Pune
3    Raj   23     88    Pune
4   Aruu   21     95  Nashik

In [24]:
df[(df["Age"]>21) & (df["Marks"]>85)]   #AND  condition

     Name  Age  Marks    City
1  Sandyy   22     90  Mumbai
3     Raj   23     88    Pune

In [25]:
df.query("Age > 21")    #query() is another way to filter data. It is often easier to read.

     Name  Age  Marks    City
1  Sandyy   22     90  Mumbai
3     Raj   23     88    Pune

In [26]:
df.query("Age > 21 and Marks > 85")

     Name  Age  Marks    City
1  Sandyy   22     90  Mumbai
3     Raj   23     88    Pune

<h3>Sorting , Ranking , Rename , Drop, Insert, Assign , Replace</h3>

In [50]:
import pandas as pd

# Create DataFrame
df = pd.DataFrame({
    "Name":["Niha","Sandyy","Khushii","Raj","Ravi"],
    "Age":[21,22,20,23,21],
    "Marks":[80,90,75,88,95],
    "City":["Pune","Mumbai","Delhi","Pune","Nashik"]
})


print(df)

      Name  Age  Marks    City
0     Niha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Ravi   21     95  Nashik

In [51]:
# Sort
print("Sorted by Marks")
print(df.sort_values(by="Marks", ascending=False))

Sorted by Marks
      Name  Age  Marks    City
4     Ravi   21     95  Nashik
1   Sandyy   22     90  Mumbai
3      Raj   23     88    Pune
0     Niha   21     80    Pune
2  Khushii   20     75   Delhi

In [52]:
# Rank
df["Rank"] = df["Marks"].rank(ascending=False)

print("Ranking")
print(df)

Ranking
      Name  Age  Marks    City  Rank
0     Niha   21     80    Pune   4.0
1   Sandyy   22     90  Mumbai   2.0
2  Khushii   20     75   Delhi   5.0
3      Raj   23     88    Pune   3.0
4     Ravi   21     95  Nashik   1.0

In [27]:
# Rename
df2 = df.rename(columns={"Marks":"Score"})

print("Renamed Column")
print(df2)

Renamed Column
      Name  Age  Score    City  Rank
0     Niha   21     80    Pune   4.0
1   Sandyy   22     90  Mumbai   2.0
2  Khushii   20     75   Delhi   5.0
3      Raj   23     88    Pune   3.0
4     Ravi   21     95  Nashik   1.0

In [53]:
# Drop column
print("Drop City")
print(df.drop("City", axis=1))

Drop City
      Name  Age  Marks  Rank
0     Niha   21     80   4.0
1   Sandyy   22     90   2.0
2  Khushii   20     75   5.0
3      Raj   23     88   3.0
4     Ravi   21     95   1.0

In [54]:
# Drop row
print("Drop First Row")
print(df.drop(0))

Drop First Row
      Name  Age  Marks    City  Rank
1   Sandyy   22     90  Mumbai   2.0
2  Khushii   20     75   Delhi   5.0
3      Raj   23     88    Pune   3.0
4     Ravi   21     95  Nashik   1.0

In [55]:
print(df.columns)

Index(['Name', 'Age', 'Marks', 'City', 'Rank'], dtype='object')

In [56]:
df.insert(1,"Gender",
          ["Male","Female","Female","Male","Male"])

print("Insert Gender")
print(df)

Insert Gender
      Name  Gender  Age  Marks    City  Rank
0     Niha    Male   21     80    Pune   4.0
1   Sandyy  Female   22     90  Mumbai   2.0
2  Khushii  Female   20     75   Delhi   5.0
3      Raj    Male   23     88    Pune   3.0
4     Ravi    Male   21     95  Nashik   1.0

In [57]:
# Assign
df3 = df.assign(Bonus=df["Marks"]+5)

print("Bonus Column")
print(df3)

Bonus Column
      Name  Gender  Age  Marks    City  Rank  Bonus
0     Niha    Male   21     80    Pune   4.0     85
1   Sandyy  Female   22     90  Mumbai   2.0     95
2  Khushii  Female   20     75   Delhi   5.0     80
3      Raj    Male   23     88    Pune   3.0     93
4     Ravi    Male   21     95  Nashik   1.0    100

In [58]:
# Replace
df["City"] = df["City"].replace({
    "Pune":"Kolhapur",
    "Delhi":"Nagpur"
})

print("Replace City")
print(df)

Replace City
      Name  Gender  Age  Marks      City  Rank
0     Niha    Male   21     80  Kolhapur   4.0
1   Sandyy  Female   22     90    Mumbai   2.0
2  Khushii  Female   20     75    Nagpur   5.0
3      Raj    Male   23     88  Kolhapur   3.0
4     Ravi    Male   21     95    Nashik   1.0

In [59]:
df.assign(
    Double=lambda x: x["Marks"]*2
)

      Name  Gender  Age  Marks      City  Rank  Double
0     Niha    Male   21     80  Kolhapur   4.0     160
1   Sandyy  Female   22     90    Mumbai   2.0     180
2  Khushii  Female   20     75    Nagpur   5.0     150
3      Raj    Male   23     88  Kolhapur   3.0     176
4     Ravi    Male   21     95    Nashik   1.0     190

In [60]:
df3 = df.assign(
    Percentage=lambda x: x["Marks"]/100*100
)

print(df3)

      Name  Gender  Age  Marks      City  Rank  Percentage
0     Niha    Male   21     80  Kolhapur   4.0        80.0
1   Sandyy  Female   22     90    Mumbai   2.0        90.0
2  Khushii  Female   20     75    Nagpur   5.0        75.0
3      Raj    Male   23     88  Kolhapur   3.0        88.0
4     Ravi    Male   21     95    Nashik   1.0        95.0

<h3>map , apply , DataFrame.map and Lambada Function</h3>

In [2]:
import pandas as pd
import numpy as np

df=pd.DataFrame({

"Name":["Nisha","Sandyy","Khushii","Raj","Priya"],

"Age":[21,22,20,23,21],

"Gender":["Male","Female","Female","Male","Female"],

"Marks":[80,90,75,88,95],

"City":["Pune","Mumbai","Delhi","Pune","Nashik"]

})
print(df)

      Name  Age  Gender  Marks    City
0    Nisha   21    Male     80    Pune
1   Sandyy   22  Female     90  Mumbai
2  Khushii   20  Female     75   Delhi
3      Raj   23    Male     88    Pune
4    Priya   21  Female     95  Nashik

In [3]:
# map using lambda

df["Age_Months"]=df["Age"].map(lambda x:x*12)
df

      Name  Age  Gender  Marks    City  Age_Months
0    Nisha   21    Male     80    Pune         252
1   Sandyy   22  Female     90  Mumbai         264
2  Khushii   20  Female     75   Delhi         240
3      Raj   23    Male     88    Pune         276
4    Priya   21  Female     95  Nashik         252

In [4]:
# map using dictionary

gender={

"Male":1,

"Female":0

}

df["Gender_Code"]=df["Gender"].map(gender)
print(df)

      Name  Age  Gender  Marks    City  Age_Months  Gender_Code
0    Nisha   21    Male     80    Pune         252            1
1   Sandyy   22  Female     90  Mumbai         264            0
2  Khushii   20  Female     75   Delhi         240            0
3      Raj   23    Male     88    Pune         276            1
4    Priya   21  Female     95  Nashik         252            0

In [5]:
# apply on Series

df["Marks_Square"]=df["Marks"].apply(lambda x:x**2)
df

      Name  Age  Gender  Marks    City  Age_Months  Gender_Code  Marks_Square
0    Nisha   21    Male     80    Pune         252            1          6400
1   Sandyy   22  Female     90  Mumbai         264            0          8100
2  Khushii   20  Female     75   Delhi         240            0          5625
3      Raj   23    Male     88    Pune         276            1          7744
4    Priya   21  Female     95  Nashik         252            0          9025

In [6]:
# apply row-wise

def result(row):

    if row["Marks"]>=85:

        return "Excellent"

    else:

        return "Average"

df["Result"]=df.apply(result,axis=1)
df

,Name,Age,Gender,Marks,City,Age_Months,Gender_Code,Marks_Square,Result
0,Nisha,21,Male,80,Pune,252,1,6400,Average
1,Sandyy,22,Female,90,Mumbai,264,0,8100,Excellent
2,Khushii,20,Female,75,Delhi,240,0,5625,Average
3,Raj,23,Male,88,Pune,276,1,7744,Excellent
4,Priya,21,Female,95,Nashik,252,0,9025,Excellent

In [7]:
# apply column-wise

print(df[["Age","Marks"]].apply(lambda col:col.max()-col.min()))

Age       3
Marks    20
dtype: int64

In [8]:
# DataFrame.map()

num=pd.DataFrame({

"A":[2.5,4.6],

"B":[6.7,8.9]

})

print(num.map(lambda x:round(x)))
df

   A  B
0  2  7
1  5  9

,Name,Age,Gender,Marks,City,Age_Months,Gender_Code,Marks_Square,Result
0,Nisha,21,Male,80,Pune,252,1,6400,Average
1,Sandyy,22,Female,90,Mumbai,264,0,8100,Excellent
2,Khushii,20,Female,75,Delhi,240,0,5625,Average
3,Raj,23,Male,88,Pune,276,1,7744,Excellent
4,Priya,21,Female,95,Nashik,252,0,9025,Excellent

<h3>~Missing Values</h3>

In [18]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name":["Nisha","Sandyy","Khushii","Raj","Ravi"],
    "Age":[21,np.nan,20,23,np.nan],              
    "Marks":[80,90,np.nan,88,95],
    "City":["Pune","Mumbai",np.nan,"Pune","Nashik"]
})

print(df)

      Name   Age  Marks    City
0    Nisha  21.0   80.0    Pune
1   Sandyy   NaN   90.0  Mumbai
2  Khushii  20.0    NaN     NaN
3      Raj  23.0   88.0    Pune
4     Ravi   NaN   95.0  Nashik

In [21]:
print("Missing Values")
print(df.isnull().sum())    #Check missing values

Missing Values
Name     0
Age      2
Marks    1
City     1
dtype: int64

In [20]:
print("Missing Values")     #Count missing values
print(df.isnull().sum())

Missing Values
Name     0
Age      2
Marks    1
City     1
dtype: int64

In [22]:
print("After dropna()")     #Remove rows/columns with missing values
print(df.dropna())

After dropna()
    Name   Age  Marks  City
0  Nisha  21.0   80.0  Pune
3    Raj  23.0   88.0  Pune

In [23]:
print("Fill Age with Mean")
df["Age"] = df["Age"].fillna(df["Age"].mean())    #Fill numeric values with average
print(df)

Fill Age with Mean
      Name        Age  Marks    City
0    Nisha  21.000000   80.0    Pune
1   Sandyy  21.333333   90.0  Mumbai
2  Khushii  20.000000    NaN     NaN
3      Raj  23.000000   88.0    Pune
4     Ravi  21.333333   95.0  Nashik

In [24]:
print("Fill Marks with Median")
df["Marks"] = df["Marks"].fillna(df["Marks"].median())    #Fill with median
print(df)

Fill Marks with Median
      Name        Age  Marks    City
0    Nisha  21.000000   80.0    Pune
1   Sandyy  21.333333   90.0  Mumbai
2  Khushii  20.000000   89.0     NaN
3      Raj  23.000000   88.0    Pune
4     Ravi  21.333333   95.0  Nashik

In [25]:
print("Fill City with Mode")
df["City"] = df["City"].fillna(df["City"].mode()[0])       #Fill text values with the most common value
print(df)

Fill City with Mode
      Name        Age  Marks    City
0    Nisha  21.000000   80.0    Pune
1   Sandyy  21.333333   90.0  Mumbai
2  Khushii  20.000000   89.0    Pune
3      Raj  23.000000   88.0    Pune
4     Ravi  21.333333   95.0  Nashik

In [26]:
print("Interpolation Example")
s = pd.Series([10, np.nan, np.nan, 40, 50])    #Estimate missing values between known values
print(s.interpolate())

Interpolation Example
0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64

<h3>~Duplicate Data</h3>

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Nisha", "Sandyy", "Khushii", "Raj", "Ravi", "Rahul"],
    "Age": [21, 22, 20, 23, 22, 23],
    "Marks": [80, 90, 75, 88, 90, 88],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Mumbai", "Pune"]
})

print(df)

      Name  Age  Marks    City
0    Nisha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Ravi   22     90  Mumbai
5    Rahul   23     88    Pune

In [2]:
print(df.duplicated())     #Checks whether each row is a duplicate    False ---> First occurrence (not considered duplicate)
                                                                 #True ---> Duplicate row

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [3]:
print(df.duplicated().sum())      #Count total duplicate rows

0

In [4]:
print(df[df.duplicated()])    #View Duplicate Rows

Empty DataFrame
Columns: [Name, Age, Marks, City]
Index: []

In [5]:
###Suppose    


df = pd.DataFrame({

"Name":["Nisha", "Sandyy", "Khushii", "Raj", "Ravi"],

"Age":[21,22,22,23,22],

"Marks":[80,90,70,88,95]

})

print(df)

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   22     70
3      Raj   23     88
4     Ravi   22     95

In [6]:
print(df.duplicated(subset=["Age"]))           #Three students have age=22
                                                  #Only the Age column is checked

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [7]:
df = pd.DataFrame({

"Name":["Nisha","Sandyy","Khushii","Raj"],

"Age":[21,22,22,23],

"Marks":[80,90,95,88]

})
df

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   22     95
3      Raj   23     88

In [8]:
print(df.duplicated(subset=["Name","Age"]))

0    False
1    False
2    False
3    False
dtype: bool

In [9]:
print("Before")

print(df)
                                          #Removes duplicate rows
print()

df2=df.drop_duplicates()

print("After")

print(df2)

Before
      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   22     95
3      Raj   23     88

After
      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   22     95
3      Raj   23     88

In [10]:
print(df.shape)

(4, 3)

In [11]:
print(df.drop_duplicates().shape)

(4, 3)

In [12]:
df.drop_duplicates()

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   22     95
3      Raj   23     88

In [13]:
df.drop_duplicates(keep="last")

      Name  Age  Marks
0    Nisha   21     80
1   Sandyy   22     90
2  Khushii   22     95
3      Raj   23     88

<h3>Complete Example</h3>

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Name":["Nisha","Sandyy","Khushii","Raj","Ravi","Rahulj"],
    "Age":[21,22,20,23,22,23],
    "Marks":[80,90,75,88,90,88],
    "City":["Pune","Mumbai","Delhi","Pune","Mumbai","Pune"]
})

print("Original Data")
print(df)

Original Data
      Name  Age  Marks    City
0    Nisha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Ravi   22     90  Mumbai
5   Rahulj   23     88    Pune

In [15]:
# Check duplicates
print("Duplicate Rows")
print(df.duplicated())

Duplicate Rows
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [16]:
# Count duplicates
print("Total Duplicates")
print(df.duplicated().sum())

Total Duplicates
0

In [17]:
# View duplicate rows
print("Duplicate Records")
print(df[df.duplicated()])

Duplicate Records
Empty DataFrame
Columns: [Name, Age, Marks, City]
Index: []

In [18]:
# Duplicate based on Age
print("Duplicate based on Age")
print(df[df.duplicated(subset=["Age"])])

Duplicate based on Age
     Name  Age  Marks    City
4    Ravi   22     90  Mumbai
5  Rahulj   23     88    Pune

In [19]:
# Remove duplicates
print("After Removing Duplicates")
print(df.drop_duplicates())

After Removing Duplicates
      Name  Age  Marks    City
0    Nisha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Ravi   22     90  Mumbai
5   Rahulj   23     88    Pune

In [20]:
# Keep last occurrence
print("Keep Last Duplicate")
print(df.drop_duplicates(keep="last"))

Keep Last Duplicate
      Name  Age  Marks    City
0    Nisha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Ravi   22     90  Mumbai
5   Rahulj   23     88    Pune

In [21]:
# Remove every duplicate
print("Remove All Duplicates")
print(df.drop_duplicates(keep=False))

Remove All Duplicates
      Name  Age  Marks    City
0    Nisha   21     80    Pune
1   Sandyy   22     90  Mumbai
2  Khushii   20     75   Delhi
3      Raj   23     88    Pune
4     Ravi   22     90  Mumbai
5   Rahulj   23     88    Pune